apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql-cluster
spec:
  replicas: 2
  secretName: mysql-secret
  backupSecretName: mysql-cluster-backup-secret
  backupURL:  s3://mysql-backups/backups/
  volumeSpec:
      persistentVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi